project: softcode-proj
virtualMachines:
  slaveNodeCount: 2
  preferManager: ""
  preferRegion: 微软 China North
  preferZone: 微软 China North
  preferHost: ""
  hypervisor: azure
  newEipBw: 100
  newEipChargeType: traffic
  network: default-1
  masterNode:
    instanceType: Basic_A1
    diskSizeGB: 40
    image: CentOS-CI-7.7.20191211
    storageBackend: standard_lrs
  slaveNode:
    instanceType: Basic_A1
    diskSizeGB: 30
    image: CentOS-CI-7.7.20191211
    storageBackend: standard_lrs
ansiblePlaybook:
  jenkins:
    hostname: localhost
    httpPort: 8080
    adminUsername: admin
    adminPassword: admin
  telegraf:
    influxdbUrl: https://cmp.chinaeast2.cloudapp.chinacloudapi.cn:30086
    influxdbName: telegraf

