project: system
virtualMachines:
  slaveNodeCount: 2
  preferManager: ""
  preferRegion: ""
  preferZone: ""
  preferHost: ""
  hypervisor: kvm
  newEipBw: ""
  newEipChargeType: ""
  network: ""
  masterNode:
    instanceType: ""
    vcpuCount: 2
    vmemSizeGB: 4
    diskSizeGB: 30
    image: CentOS-CI-7.7.20191211
    storageBackend: ""
  slaveNode:
    instanceType: ""
    vcpuCount: 2
    vmemSizeGB: 4
    diskSizeGB: 30
    image: CentOS-CI-7.7.20191211
    storageBackend: ""
ansiblePlaybook:
  jenkinsHostname: localhost
  jenkinsHttpPort: 8080
  jenkinsAdminUsername: admin
  jenkinsAdminPassword: admin
  telegrafInfluxdbUrl: ""

