{{- $vms := .Values.virtualMachines}}
{{- $name := .Release.Name -}}
{{- $project := .Values.project }}
{{- $node := $vms.slaveNode -}}
{{- $count := $vms.slaveNodeCount -}}
{{- range $i, $e := until ($count | int) }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: jk-{{ $name }}-slave{{ add $e 1 }}
spec:
  description: Jenkins slave node No.{{ add $e 1 }}
  projectConfig:
    project: {{ $project }}
  vmConfig:
    {{- if $vms.preferManager }} 
    preferManager: {{ $vms.preferManager }} 
    {{- end }}
    {{- if $vms.preferRegion }} 
    preferRegion: {{ $vms.preferRegion }} 
    {{- end }}
    {{- if $vms.preferZone }} 
    preferZone: {{ $vms.preferZone }} 
    {{- end }}
    {{- if $vms.preferHost }} 
    preferHost: {{ $vms.preferHost }} 
    {{- end }}
    hypervisor: {{ $vms.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      image: {{ $node.image }}
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if $vms.network }}
    networks:
      - network: {{ $vms.network }}
    {{- end }}
  {{- if or $vms.newEipBw $vms.newEipChargeType }}
  newEip:
    {{- if $vms.newEipBw }}
    bw: {{ $vms.newEipBw }}
    {{- end }}
    {{- if $vms.newEipChargeType }}
    chargeType: {{ $vms.newEipChargeType }}
    {{- end }}
  {{- end}}

---

{{- end }}
