{{- $vms := .Values.virtualMachines}}
{{- $name := .Release.Name -}}
{{- $node := $vms.slaveNode -}}
{{- $count := $vms.slaveNodeCount -}}
{{- range $i, $e := until ($count | int) }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: jk-{{ $name }}-slave{{ add $e 1 }}
spec:
  description: Jenkins slave node No.{{ add $e 1 }}
  projectConfig:
    project: {{ $vms.project }}
  vmConfig:
    hypervisor: {{ $vms.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      image: Java-CentOS-7.6.qcow2
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if $vms.network }}
    neworks:
      - network: {{ $vms.network }}
    {{- end }}

---

{{- end }}
