{{- $vms := .Values.virtualMachines}}
{{- $name := .Release.Name -}}
{{- $node := $vms.masterNode -}}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: jk-{{ $name }}-master
spec:
  description: Jenkins master node
  projectConfig:
    project: {{ $vms.project }}
  vmConfig:
    {{- if $vms.preferManager }} 
    preferManager: {{ $vms.preferManager }} 
    {{- end }}
    {{- if $vms.preferRegion }} 
    preferRegion: {{ $vms.preferRegion }} 
    {{- end }}
    {{- if $vms.preferZone }} 
    preferZone: {{ $vms.preferZone }} 
    {{- end }}
    {{- if $vms.preferHost }} 
    preferHost: {{ $vms.preferHost }} 
    {{- end }}
    hypervisor: {{ $vms.hypervisor }}
    {{- if $node.instanceType }}
    instanceType: {{ $node.instanceType }}
    {{- else }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    {{- end }}
    rootDisk:
      image: Jenkins-Telegraf-CentOS-7.6.qcow2
      sizeGB: {{ $node.diskSizeGB }}
      {{- if $node.storageBackend }} 
      storageConfig:
        backend: {{ $node.storageBackend }}
      {{- end }}
    {{- if $vms.network }}
    neworks:
      - network: {{ $vms.network }}
    {{- end }}

    {{- if $node.eip }}
    eip: {{ $node.eip }}
    {{- end }}
    {{- if or $node.newEipBw $node.newEipChargeType }}
    newEip:
      {{- if $node.newEipBw }}
      bw: {{ $node.newEipBw }}
      {{- end }}
      {{- if $node.newEipChargeType }}
      chargeType: {{ $node.newEipChargeType }}
      {{- end }}
    {{- end}}
