{{- $vms := .Values.virtualMachines}}
{{- $name := .Release.Name -}}
{{- $node := $vms.slaveNode -}}
{{- $count := $vms.slaveNodeCount -}}
{{- range $i, $e := until ($count | int) }}
apiVersion: onecloud.yunion.io/v1
kind: VirtualMachine
metadata:
  name: jk-{{ $name }}-slave{{ add $e 1 }}
spec:
  description: Jenkins slave node No.{{ add $e 1 }}
  projectConfig:
    project: {{ $vms.project }}
  vmConfig:
    hypervisor: {{ $vms.hypervisor }}
    vcpuCount: {{ $node.vcpuCount }}
    vmemSizeGB: {{ $node.vmemSizeGB }}
    rootDisk:
      image: CentOS-7.6.1810-20190430.qcow2
      sizeGB: {{ $node.diskSizeGB }}
    {{- if $vms.network }}
    neworks:
      - network: {{ $vms.network }}
    {{- end }}

---

{{- end }}
